[package]
name = "pakka"
version = "0.1.0"
edition = "2021"
description = "A cross platform meta package manager with optional snapshotting file system based transactions"

[dependencies]
clap = "4"
chrono = "0.4"
